# Generated by Django 5.0.6 on 2024-05-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_locater_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busroute',
            options={'ordering': ['bus_route_name']},
        ),
        migrations.RemoveField(
            model_name='college',
            name='bus_route',
        ),
        migrations.AddField(
            model_name='busroute',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_locater_app.college'),
        ),
    ]
