# Generated by Django 5.0.6 on 2024-05-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_locater_app', '0002_alter_busroute_options_remove_college_bus_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busroute',
            name='college',
        ),
        migrations.DeleteModel(
            name='College',
        ),
    ]
